# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-09 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='typeofuser',
            field=models.CharField(default='student', max_length=7),
        ),
    ]
