# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-09 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20190309_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='typeofuser',
        ),
    ]
