# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-09 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_user_info_typeofuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='type_of_user',
            field=models.CharField(choices=[('mentor', 'MENTOR'), ('student', 'STUDENT')], default='student', max_length=250),
        ),
    ]
