# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-08 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_user_info_type_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='type_of_user',
            field=models.CharField(choices=[('mentor', 'MENTOR'), ('student', 'STUDENT')], max_length=250),
        ),
    ]
