# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-09 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_pairing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairing',
            name='Ack1',
            field=models.BooleanField(default=True),
        ),
    ]
