# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-09 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20190309_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='facebook',
            field=models.CharField(default='facebook', max_length=50),
        ),
    ]
