# Generated by Django 2.1.7 on 2019-03-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20190308_1305'),
        ('my_app', '0009_auto_20190309_1031'),
    ]

    operations = [
    ]
